name: Deploy container to Azure Functions App

on:
  push:
    branches:
      - main
    paths:
      - 'C_Sharp/API2/**'
  workflow_dispatch:


jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   environment: dev
   steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Set Environment Variables'
      run: |
        echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/C_Sharp/API2
        acrName: api2reginame
        containerAppName: newcontainer-api2
        resourceGroup: 519fall2023-project-BIAN
        environmentVariables: |
          newsetting=secretref:storageconnectionstring
