name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: ./Node/WEB

    # Conditionally run build if script exists
    - name: Run Build if Script Exists
      run: |
        if npm run | grep -q build; then
          npm run build
        fi
      working-directory: ./Node/WEB

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yuhe'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './Node/WEB'
