name: Deploy Node Web App to Azure

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # use the Node.js version you want

    - name: Install Dependencies
      run: |
        cd Node/WEB
        npm install

    - name: Build project  # only if you need to build your frontend
      run: |
        cd Node/WEB/frontend
        npm install  # if you have separate package.json for frontend
        npm run build  # or your build command

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-azure-app-name'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Node/WEB  # directory to be deployed
