name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install server dependencies
      run: npm install
      working-directory: ./Node/WEB

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm install
        npm run build
      working-directory: ./Node/WEB

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yuheb-web'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./Node/WEB  # or the directory containing your built application
