name: Deploy to Azure

on:
  push:
    branches:
      - main  # change to your branch
    paths:
      - 'C_Sharp/WEB/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # update to your version
    
    - name: Build Project
      run: dotnet build --configuration Release ./C_Sharp/WEB
      
    - name: Publish Project
      run: dotnet publish -c Release -o ./published ./C_Sharp/WEB
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: cs-new
        slot-name: 'production' # optional
        package: ./published
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
