name: Deploy to Azure

on:
  push:
    branches:
      - main  # change to your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # use the Node.js version you want
    
    - name: Build Project
      run: dotnet build --configuration Release ./C_Sharp/WEB/WEB.csproj
      
    - name: Publish Project
      run: dotnet publish -c Release -o ./published ./C_Sharp/WEB/WEB.csproj
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: C-new
        slot-name: 'production' # optional
        package: ./published
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
